### ISSUE TITLE
Bismark and USCS tools wrapper

### ISSUE THREAD

**Issue by iromeo** [snakemake/snakemake-wrappers#1]
I've already submitted related Pull Requests into old repo:
* https://bitbucket.org/snakemake/snakemake-wrappers/pull-requests/105/wrappers-for-bismark-methylation-analysis/diff
* https://bitbucket.org/snakemake/snakemake-wrappers/pull-requests/106/wrappers-for-some-of-ucsc-tools/diff

Do I need to resubmit the PR here?

**Comment by johanneskoester** [comment]
I am so sorry, but somehow I forgot to go through those PRs. Would you mind resubmitting them here? I can also do that manually, since it is entirely my fault.

**Comment by iromeo** [comment]
> Would you mind resubmitting them here?
Yes, I'll do, not a problem.

**Comment by johanneskoester** [comment]
Thanks a lot!
