### ISSUE TITLE
RSEM Calculate Expression bug for paired-end bam file input

### ISSUE THREAD

**Issue by isaacvock** [snakemake/snakemake-wrappers#1074]
In the documentation for the [rsem-calculate-expression wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/rsem/calculate-expression.html), the params block includes `paired_end=True` as an example of what needs to be included if passing a bam file from aligned paired end reads as input. In the actual wrapper script though, this parameter is fetched as `paired_end=snakemake.params.get("paired-end", False)`. This is both a problem because it clashes with the parameter name used in the documentation, but also I believe parameter names can't have hyphens, so changing the documentation to `paired-end=True` is probably fraught. Thus, I think the wrapper code needs to be modified to `paired_end=snakemake.params.get("paired_end", False).

**Comment by fgvieira** [comment]
Hi @isaacvock, thanks for reporting the bug. Do you think you could do a PR?

**Comment by isaacvock** [comment]
Will do!

**Comment by fgvieira** [comment]
thanks!

**Comment by isaacvock** [comment]
I got it to run with bam files from paired-end data aligned with STAR in a separate, upstream rule. I have not tried with fastqs as input.

It is probably worth including more details about the errors you are getting and/or problems that you are running into with this particular use-case. In the meantime, I'll try and run the wrapper with paired-end fastqs as input and see if I run into any similar problems.

**Comment by KuechlerO** [comment]
Hi @isaacvock,
thx for the quick answer, I see.

Kay, actually I was able to make it run.
However, when using the wrapper one needs to take into consideration:
When fastq-files are used as input, one needs to provide a bowtie-index. I suspect that in that case the creation of the RSEM-index with the "RSEM prepare reference"-wrapper is not necessary.

But I need to take a closer look into that.
Maybe the wrapper examples could be split into 2 cases then: One using pre-aligned results, the other one not.
