### ISSUE TITLE
Sickle se/pe

### ISSUE THREAD

**Issue by incardon** [snakemake/snakemake-wrappers#1125]
The Snakemake file in the test folder of sickle/se is:

rule sickle_pe:
  input:
    "input_R1.fq"
  output:
    "output_R1.fq"
  params:
    qual_type="sanger",
    # optional extra parameters
    extra=""
  log:
    "logs/sickle/job.log"
  wrapper:
    "master/bio/sickle/pe"

I immagine should be:

rule **sickle_se**:
  input:
    "input_R1.fq"
  output:
    "output_R1.fq"
  params:
    qual_type="sanger",
    # optional extra parameters
    extra=""
  log:
    "logs/sickle/job.log"
  wrapper:
    "**master/bio/sickle/se**"

**Comment by fgvieira** [comment]
Fixed on #1126
