### ISSUE TITLE
cutadapt no such option -j

### ISSUE THREAD

**Issue by RoebideBruijn** [snakemake/snakemake-wrappers#114]
I've used snakemake version 5.19.2 and cutadapt wrapper version 0.60 (cutadapt version 1.9.1) .

I got an error when running my rule cutadapt that still worked a couple of months ago. From the logfile:
`cutadapt: error: no such option: -j` (the threads option)

rule in *.smk file:
```
rule cutadapt:
    input:
        "fastq/raw/{unit}.R1.fastq.gz"
    output:
        fastq=temp("fastq/trimmed/{unit}.R1.fastq.gz"),
        qc="qc/cutadapt/{unit}.txt"
    params:
        cutadapt_extra
    log:
        "logs/cutadapt/{unit}.log"
    wrapper:
        "0.60.0/bio/cutadapt/se"

```
Configfile:
```
    cutadapt:
        extra:
            - "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
```

**Comment by jafors** [comment]
Hi @RoebideBruijn ,
strange. Normally, when using the wrapper version 0.60.0 (or 0.51.0 as in your example), the cutadapt version should be 2.5. The 1.9.1 version of cutadapt does not have the -j option, which is probably the source of your error.

To me, it looks like you are running the code in the wrapper without using the correct cutadapt version. Did you use `--use-conda` when calling snakemake?

**Comment by RoebideBruijn** [comment]
Ah that's it, sorry stupid mistake. I was thinking: must be something I did. But no idea what it could be haha.

**Comment by jafors** [comment]
No worries! Closing this then.
