### ISSUE TITLE
Support threads directive with fastqc

### ISSUE THREAD

**Issue by CharlesJB** [snakemake/snakemake-wrappers#116]
**Is your feature request related to a problem? Please describe.**

I was wondering why the `fastqc` wrapper is not using the `threads` directive unlike other tools such as `bwa mem`.

**Describe the solution you'd like**

Could the wrapper be modified to use the `threads` directive?

**Describe alternatives you've considered**

Right now I'm using the `params` directive with `-t 8` alongside `threads: 8` for it to work on my HPC infrastructure, but I would like to avoid hardcoding the number of threads I'm using.

**Comment by jafors** [comment]
Thanks for that catch! This has been addressed in #117
