### ISSUE TITLE
Salmon Quant wrapper throwing segmentation fault

### ISSUE THREAD

**Issue by oligomyeggo** [snakemake/snakemake-wrappers#1167]
**Snakemake version**
snakemake = 7.18.2
snakemake-wrappers-util = 0.5.0

**Describe the bug**
Using the [Salmon Quant wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/salmon/quant.html) (v1.25.0) throws `Segmentation fault (core dumped)`. This occurs when using a single pair of fastq files or multiple fastq files for a single sample.

**Additional context**
Currently, the Salmon Quant wrapper is using Salmon v1.9.0 from bioconda. From [this issue](https://github.com/COMBINE-lab/salmon/issues/829), it looks like there might be problems with the Salmon v1.9.0 bioconda build which seem to be resolved by pulling the latest version of Salmon (v1.10.1) from bioconda. [Another issue](https://github.com/COMBINE-lab/salmon/issues/835) also indicates that Salmon v1.10.1 fixes segmentation fault issues.

Could we update the Salmon Quant wrapper to pull Salmon v1.10.1 from bioconda? The Salmon Index wrapper is already updated to v1.10.1.

**Comment by Austin-s-h** [comment]
Would also love to see this!
