### ISSUE TITLE
Possible bowtie2 align bug

### ISSUE THREAD

**Issue by smped** [snakemake/snakemake-wrappers#1396]
**Snakemake version**
7.26.0

**Describe the bug**
I can't run the wrappers on my HPC so I have downloaded the script and am running locally. However in v1.31.1 of the [bowtie align wrapper](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/bowtie2/align/wrapper.py) (when running as a local script) I get a failure in line44, with message that the object has no `.endswith` attribute, which I assume is because it is a list. I fixed this in my local version by changing lines 43-52 to:

```
if n == 1:
    if get_format(snakemake.input.sample[0]) in ("bam", "sam"):
        reads = f"-b {snakemake.input.sample[0]}"
    else:
        if snakemake.params.get("interleaved", False):
            reads = f"--interleaved {snakemake.input.sample[0]}"
        else:
            reads = f"-U {snakemake.input.sample[0]}"
else:
    reads = "-1 {} -2 {}".format(*snakemake.input.sample)
```

I'm an R user and am pretty out of my depth with python, but I hope that's vaguely helpful. Obviously just close this feature if that's a quirk of me running this locally, not as a wrapper

**Comment by fgvieira** [comment]
Are you running it with SE reads?
If so, I found the same thing and I've fixed it on #1395

**Comment by smped** [comment]
Yes! Sorry, I forgot to mention that. Pleased to hear someone's onto it

**Comment by fgvieira** [comment]
The fix has been merged. Can you check if it works for you?

**Comment by tdayris** [comment]
Bug fixed for me. Thanks !
