### ISSUE TITLE
conda-forge is not priority channel for many wrappers

### ISSUE THREAD

**Issue by SilasK** [snakemake/snakemake-wrappers#161]
**Is your feature request related to a problem? Please describe.**

If I remember correctly the order of channels has a big impact on the performance of the install process. 
conda-forge should be prioritized over bioconda.

many wrappers have it the other way around. 

**Describe the solution you'd like**
have consistent channel priorities in al environement.aml files
If I remember correctly this is the optimal solution.
```
channels:
  - conda-forge
  - bioconda
  - defaults
```
**Describe alternatives you've considered**
I know mamba is another solution

**Additional context**

I can help, if this change is accepted.

**Comment by fgvieira** [comment]
Closing since this has already been fixed with the change to strict channel priority (#503 and #508).
