### ISSUE TITLE
Wrappers using unnamed params break cluster params

### ISSUE THREAD

**Issue by lkuchenb** [snakemake/snakemake-wrappers#176]
Some wrappers, e.g. `samtools sort` or `samtools index` consume params entirely to customize tool invocation. Others, like `trim_galore-pe` use a named param called `extra`.

The latter allows the specification of additional params for cluster execution as suggested [in the documentation](https://snakemake.readthedocs.io/en/stable/executing/cluster.html), the former breaks when additional named params are used. I'm not sure if there are use cases for additional params other than `--cluster`, as they are obviously not going to be used in the rule code itself.

**Comment by lkuchenb** [comment]
@jafors Ah good. That one didn't come up in my issue searches ;-) I'll close this one then.

**Comment by johanneskoester** [comment]
@lkuchenb that part of the docs was a bit outdated, sorry. Such properties should now rather be specified via `resources` instead of `params`. Params is really only for stuff that is platform independent. Hence, a missing `extra` should not hurt.

**Comment by johanneskoester** [comment]
I have updated the docs, changes will show up in the next release.

**Comment by lkuchenb** [comment]
Nice, that's good to know. Thanks.
