### ISSUE TITLE
Improper quoting of log file in fastqc wrapper

### ISSUE THREAD

**Issue by ManavalanG** [snakemake/snakemake-wrappers#191]
**Snakemake version**
snakemake version: `0.63.x` onwards

**Describe the bug**
Log filepath gets improperly quoted for fastqc wrapper,  and hence its logs won't be written into a file. Note that job using this wrapper will be successful (unless singularity container is used) but the log file will be empty.

**Logs**

```
$snakemake --use-conda -f qc/fastQC/before_trim/rep1_R1_fastqc.html -p

....
....

python /workflow_path/.snakemake/scripts/tmpsz98rhl8.wrapper.py
Activating conda environment:/workflow_path/.snakemake/conda/06b7292e
fastqc  --quiet -t 1 --outdir /scratch/local/tmpenzw80c2/workflow_path/rep1_R1.fastq.gz ' 2> logs/fastQC/rep1_R1.log'
Skipping ' 2> logs/fastQC/rep1_R1.log' which didn't exist, or couldn't be read
mv /scratch/local/tmpenzw80c2/rep1_R1_fastqc.html qc/fastQC/before_trim/rep1_R1_fastqc.html
mv /scratch/local/tmpenzw80c2/rep1_R1_fastqc.zip qc/fastQC/before_trim/rep1_R1_fastqc.zip
[Tue Sep 22 17:14:16 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log:/workflow_path/.snakemake/log/2020-09-22T171404.568908.snakemake.log
```

**Minimal example**
Try using `0.62.0` and `0.66.0` to replicate the issue. Former should be problem-free (assuming other dir/filepaths dont have whitespace character). 

**Additional context**

https://github.com/snakemake/snakemake-wrappers/blob/517d848791a27909e76030d645e9fffbbcc94516/bio/fastqc/wrapper.py#L32-L34

In version `0.63.0`, log directive was quoted using snakemake's `:q` feature, and this has the side effect of quoting not just the filepath but also the redirection symbol.

**Comment by fgvieira** [comment]
@ManavalanG I believe this bug is fixed in the latest wrapper version:
https://github.com/snakemake/snakemake-wrappers/blob/efaf381911dd5d9d6a3cddc63184b32744741b17/bio/fastqc/wrapper.py#L38-L40

Can you confirm?

**Comment by ManavalanG** [comment]
@fgvieira From quick glance, yes :)
