### ISSUE TITLE
`bcftools merge`: not able to declare dependency on index files

### ISSUE THREAD

**Issue by votti** [snakemake/snakemake-wrappers#2295]
**Snakemake version**
- snakemake: 7.32.4
- snakemake_warppers: master/v2.9.1
 
**Describe the bug**
`bcftools merge` requires indices for input files to be merged.

Previously it has been possible to explicitly declare dependencies on indices for `bcftools merge` using additional inputs, thus enabling Snakemake to generate them.
An example in the wild is: https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling/blob/80d1662ac47af59cf0e89856c1f5b573f186956b/workflow/rules/calling.smk#L129-L182

This behavior has been changed as now all `inputs` in this wrapper are joined, causing an error as the model tries to merge the index files.

**Logs**
[E::hts_hopen] Failed to open file a.bcf.csi
[E::hts_open_format] Failed to open file "a.bcf.csi" : Exec format error
Failed to open a.bcf.csi: Exec format error

**Minimal example**
A test example has been added in this branch: https://github.com/snakemake/snakemake-wrappers/compare/master...FroeseLab:snakemake-wrappers:bug/mergeindex

**Additional context**
The solution would be to:
- only use `calls` inputs as inputs (potentially breaking backwards compatibility)
or
- adding new input field `indices` that is explicitly excluded from being interpreted as an input (less likely to break backwards compatiblity)

**Comment by johanneskoester** [comment]
thansk for reporting!
