### ISSUE TITLE
the output files generated by using STAR in snakemake-wrappers should be more comprehensive.

### ISSUE THREAD

**Issue by zhongzheng1999** [snakemake/snakemake-wrappers#2756]
I'm currently working on setting up a simple RNA-seq analysis pipeline using snakemake, and I've integrated the STAR wrapper from snakemake-wrappers. However, I've run into an issue where specifying `--quantMode TranscriptomeSAM `prevents me from extracting the `Aligned.toTranscriptome.out.bam` file as an output. I believe this file is essential for subsequent transcript quantification.

After examining the corresponding `wrapper.py` file, I noticed that within the `with tempfile.TemporaryDirectory() as tmpdir: `block, you use the `cat` command to output specific temporary files as result files. However, I observed that you only provided options such as `ReadsPerGene.out.tab`, `Chimeric.out.junction`, `SJ.out.tab`, `etc.`, but there is no code for outputting `Aligned.toTranscriptome.out.bam.`

**Comment by zhongzheng1999** [comment]
When I use the --outStd BAM_SortedByCoordinate parameter, the output for {snakemake.output.aln} is the Aligned.out.bam file. However, I'm wondering if using --quantMode TranscriptomeSAM would mean that Aligned.toTranscriptome.out.bam is output instead of Aligned.out.bam. I've checked the STAR documentation but couldn't find an explanation for this issue.

**Comment by zhongzheng1999** [comment]
@kashyapchhatbar @fgvieira

**Comment by fgvieira** [comment]
From STAR's manual:

> With `--quantMode TranscriptomeSAM` option STAR will output alignments translated into transcript coordinates in the `Aligned.toTranscriptome.out.bam` file (in addition to alignments in genomic coordinates in `Aligned.*.sam/bam` files).

So, I'd say that a new file is created. Can you double-check it?

**Comment by fgvieira** [comment]
If you modified `wrapper.py`, it would be great if you could submit a PR.
