### ISSUE TITLE
bowtie2_build wrapper produces wrong output name for large index

### ISSUE THREAD

**Issue by katkopera** [snakemake/snakemake-wrappers#277]
**Snakemake version**
snakemake 5.30.1
wrapper:
        "0.68.0/bio/bowtie2/build"

**Describe the bug**
When running a large index through the bowtie2_build, wrapper appends extra "l" in the middle of the index base name which results in output like:
bowtie2/index/**rep82l**.1.bt2l       SHOULD BE bowtie2/index/**rep82**.1.bt2l
bowtie2/index/**rep82l**.2.bt2l       SHOULD BE bowtie2/index/**rep82**.2.bt2l
....
....
....
bowtie2/index/rep82**l**.rev.2.bt2l  SHOULD BE bowtie2/index/**rep82**.rev.2.bt2l

which further results in MissingOutputException as output is different from expected. 

**Logs**
MissingOutputException in line 77 of /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT/Snakefile:
Job Missing files after 5 seconds:
bowtie2/index/rep82.1.bt2l
bowtie2/index/rep82.2.bt2l
bowtie2/index/rep82.3.bt2l
bowtie2/index/rep82.4.bt2l
bowtie2/index/rep82.rev.1.bt2l
bowtie2/index/rep82.rev.2.bt2l
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 4 completed successfully, but some output files are missing.

**Minimal example**
```
rule bowtie2_build:
    input:
        reference="prebuilt_data/rep82.fna"
    output:
        multiext(
            "bowtie2/index/rep82",
            ".1.bt2l", ".2.bt2l", ".3.bt2l", ".4.bt2l", ".rev.1.bt2l", ".rev.2.bt2l",
        ),
    log:
        "logs/bowtie2_build/build.log"
    params:
        extra="--large-index"  # optional parameters
    threads: 10
    wrapper:
        "0.68.0/bio/bowtie2/build"
```
Could it be possible to fix this bug as it prevents from using the wrapper for large index?

**Comment by johanneskoester** [comment]
Fixed by #469
