### ISSUE TITLE
Versions, citations and references for tools being used

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake-wrappers#287]
**Is your feature request related to a problem? Please describe.**
I am currently writing a manuscript that uses snakemake with a lot of wrapper scripts, and have to go through all tools individually to get (a) the exact version of the tool, and (b) then look up its reference for the bibliography.

My process is: 

 - Go through all my snakemake files and all rules and tools being used. For each of them:
 - Find the wrapper version:
   ```
   wrapper:
           "0.51.3/bio/trimmomatic/pe"
   ```
 - Find the documentation at that exact version of the wrapper: https://snakemake-wrappers.readthedocs.io/en/0.51.3/wrappers/trimmomatic/pe.html
 - Get the version of the tool being used from there.
 - Do a Google Scholar search for the tool to get its preferred citation/reference.
 - Then, put this into text: "We used trimmomatic v0.36 [1]", etc...

This is repetitive work, not only for me, but for everyone who is in a similar situation. The two pieces of information that I am interested in here are the version of the tool being used, and its reference.

**Describe the solution you'd like**
Ideally, snakemake could offer some command that takes a config file/workflow, and figures out all tools being used in that exact workflow configuration (skipping any rules that are not being invoked!). It then automatically collects the needed information, and prints it in some format. 

Tool version information is already available via the `environment.yaml` in the wrapper, and citation or links to the tool websites could be added (optionally and bit by bit for each tool) to the `meta.yaml` and read from there.

I guess that this is only feasible for wrapped tools, and that I still have to go through my individual (shell/script based) rules. But the above snakemake command then could at least also list all those rules, so that I do not forget about them. Basically, it prints out a linear list of the dependency graph (similar to the normal terminal output when running snakemake, but only once for each rule), but with all tools and references listed.

So, my ideal solution would look something like this:

    $ snakemake [...] --print-tools # or whatever you would want to call this command
    Rule `trim_read`:
        - Uses wrapper `TRIMMOMATIC PE`
        - Tool: trimmomatic v0.36
        - Conda: https://anaconda.org/bioconda/trimmomatic
        - URL: http://www.usadellab.org/cms/index.php?page=trimmomatic
        - Reference: Bolger, A. M., Lohse, M., & Usadel, B. (2014). Trimmomatic: A flexible trimmer for Illumina sequence data. Bioinformatics, 30(15), 2114–2120. https://doi.org/10.1093/bioinformatics/btu170
    Rule `my_rule`:
        - Uses shell-based command
    Rule `my_other_rule`:
        - Uses python-based command
    ....

That would be awesome!

**Describe alternatives you've considered**
I thought that a simple overview table here in the repo might also be a solution, but that would get too messy rather quickly, with all wrappers in different versions etc... and it would not really speed things up, would be extra maintenance work, and would probably be outdated all the time, and... No, not a good alternative.

**Comment by lczech** [comment]
I have also opened this issue in [the snakemake repository](https://github.com/snakemake/snakemake/issues/864). Feel free to close one of them - I wasn't quite sure what the best place to put this is.

**Comment by dlaehnemann** [comment]
I think this best fits into snakemake reports, so I have commented over in the snakemake repo and will close this here, for now:
https://github.com/snakemake/snakemake/issues/864#issuecomment-869504136
