### ISSUE TITLE
fastqc: Identify correct file extensions

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake-wrappers#288]
**Snakemake version**
Snakemake: 5.31.1
Wrappers: stable and 0.70.0
fastqc==0.11.9

**Describe the bug**
The wrapper [contains code](https://github.com/snakemake/snakemake-wrappers/blob/52c4a4a4a8fb388e68b46c0a9982432ef86cd071/bio/fastqc/wrapper.py#L22-L23) that checks and removes file extensions:

    split_ind = 2 if base.endswith(".fastq.gz") else 1
    base = ".".join(base.split(".")[:-split_ind])

This does not take care of the also quite common fastq `.fq` extension in case it's gzipped, so `.fq.gz` is not recognized, as well as other formats recognized by fastqc. The effect is that the subsequent file move operation does not succeed, as the file name used by the wrapper script does not match the file name produced by fastqc. This leads to the rule failing in snakemake.

Proposed solution: Follow the [actual file extension removal code that fastqc uses](https://github.com/s-andrews/FastQC/blob/bfde9d31aa94f29e9c58b6e91574a08e57335a4a/uk/ac/babraham/FastQC/FastQCApplication.java#L238), so that the wrapper matches that:

    # At the top of the file
    import re

    # Instead of the two lines above:
    base = re.sub('\\.gz$', '', base)
    base = re.sub('\\.bz2$', '', base)
    base = re.sub('\\.txt$', '', base)
    base = re.sub('\\.fastq$', '', base)
    base = re.sub('\\.fq$', '', base)
    base = re.sub('\\.sam$', '', base)
    base = re.sub('\\.bam$', '', base)

This might need to be updated if fastqc changes their input/output file naming, but should be stable for now.

**Comment by johanneskoester** [comment]
Thanks for reporting. PR #300 has been merged.
