### ISSUE TITLE
snakemake wrapper mirror 

### ISSUE THREAD

**Issue by WWz33** [snakemake/snakemake-wrappers#2988]
Hi Snakemake team！
First of all, thank you for providing such a great tool！
I am from China， and for some reason, we have slow access to GitHub.
When I used Snakemake, I used to get this error.
e.g：`Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/0.51.3/bio/samtools/index/environment.yaml`
And I'm a non-Root user, so I can't set up a web proxy.
Is there a way to make **snakemake-wrappers** point to other **mirrors**, such as [Gitee](https://gitee.com/)?

Best!

**Comment by fgvieira** [comment]
You can specify another wrapper location with `--wrapper-prefix` (see https://snakemake.readthedocs.io/en/stable/executing/cli.html). You can use another URL (e.g. your own GitHub repo) or a local clone of the repo.

**Comment by WWz33** [comment]
thans .i got it 😊

Filipe G. Vieira ***@***.***> 于 2024年6月8日周六 23:49写道：
