### ISSUE TITLE
samtools version is wrong in `0.15.3/bio/bwa/mem/`.

### ISSUE THREAD

**Issue by manji2001** [snakemake/snakemake-wrappers#3004]
**Snakemake version**
8.14.0

**Describe the bug**

`samtools ==1.2` is wrong in wsl2 Ubuntu 22.04.3, `samtools ==1.20` is ok

**Logs**
```bash
$ samtools --version
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
**Minimal example**
```bash
mamba create -n test samtools==1.2`
mamba activate test
samtools --version
```

**Comment by fgvieira** [comment]
That is an old version. Have you tried with the latest?

**Comment by manji2001** [comment]
> That is an old version. Have you tried with the latest?

No. I'm a beginner and I'm learning according to the official tutorial. I found it in [this tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#tool-wrappers).
I think this wrong code snippet will confuse other beginners, so I opened this issue, hoping it could be corrected.
In fact, there is another error in that tutorial. `"-R '@RG\tID:{sample}\tSM:{sample}'"` won't run correctly as will, because the `\t` will be converted when running. I have created a [pull request](https://github.com/snakemake/snakemake/pull/2922) to correct it.

**Comment by fgvieira** [comment]
But then it is a `snakemake` documentation issue, not a bug, right?

**Comment by manji2001** [comment]
You are ritht. Maybe I should open an issue for snakemake.
