### ISSUE TITLE
hisat2 align wrapper ht2l extension

### ISSUE THREAD

**Issue by gilless429** [snakemake/snakemake-wrappers#3368]
When using the hisat2 wrappers, I run into issues if my reference genome is large. This is because the hisat2 indexation will create ht2l files in this instance, not ht2, and the hisat2 align wrapper uses .glob("*.ht2") (line 29 of the current wrapper.py) and as such does not grab any ht2l files.

It seems to me adding to the ht2_files variable any files that match .ht2l via .glob("*.ht2l") as well would solve the problem.

It could also be considered to add a parameter to specify whether the genome used is large in the rule, but this seems a little too manual for the user in my opinion, when there don't really seem to be any issues with grabbing all .ht2 and .ht2l files.

This happens to me when using the wheat reference genome for example, which is quite large.

**Comment by fgvieira** [comment]
Well, the proper way would be to specify the files you want to use as index, and then infer the path from them.
Do you think you could make a PR?

**Comment by gilless429** [comment]
This works to allow .ht2l index files, but it seems to have the (rather significant, in my opinion) downside of requiring that the user know ahead of time what their index output is going to look like, whereas in automated pipelines the indexing will often be done blind then followed up immediately by mapping.
A user would have to know ahead of time what their index is going to look like and say so, or the pipeline would need to peek into the requisite folder and see what they look like before getting on with alignment (and the peek would need to happen AFTER the indexing is done).
Obviously when using wheat (massive genome) it's 100% of the time going to be ht2l, and with something like Arabidopsis thaliana it'll always be ht2, but for the genomes in the neighborhood of that 4 gigabases approximate threshold (or for users who just have no idea about this threshold), this gets a little more dicey for automation.

The perk of a .glob() type approach is that as long as you put your indexation files in their own folder, not shared with other index files - which should be done anyway - you can just point snakemake to it, have the wrapper look for either ht2 or ht2l files, and go from there.

**Comment by fgvieira** [comment]
I find globbing a bit dangerous as you never know what other files might be in the same folder.
In your case, what about forcing the index to always be `.ht2l`?
