### ISSUE TITLE
using ensemblgenomes for non-vertebrate references

### ISSUE THREAD

**Issue by RvV1979** [snakemake/snakemake-wrappers#341]
Hi Johannes, 
I am trying to implement the https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling workflow for non-vertebrate (plant) genomes that are available through ensemblgenomes.org. However, the  https://github.com/snakemake/snakemake-wrappers/tree/master/bio/reference wrappers use only the canonical ensembl ftp site. 

Is it possible to use these wrappers for ensemblgenomes ?

Thanks

**Comment by fgvieira** [comment]
The wrapper currently uses the URL `ftp://ftp.ensembl.org/pub/{branch}release-{release}/fasta/{species}/{datatype}/{species_cap}.{spec}.{suffix}`.

For ensembl genomes, would it be enough to change it to `ftp://ftp.{source}.org/pub/{branch}release-{release}/fasta/{species}/{datatype}/{species_cap}.{spec}.{suffix}`?

Can you provide an example snakemake rule for testing?

**Comment by fgvieira** [comment]
I believe this has been fixed on #546.
Can you double check?
