### ISSUE TITLE
SonarCloud Code Inspections profile is very confusing

### ISSUE THREAD

**Issue by iromeo** [snakemake/snakemake-wrappers#35]
SonarCloud inspections aren't configured properly for this project, so current master and all recent wrappers releases (e.g. v0.41.0) are marked as "Failed" by SonarCloud
![image](https://user-images.githubusercontent.com/72933/70129198-54610400-168f-11ea-9aca-26e6a886df3c.png)

In detail, SonarCloud doesn't understand that `snakemake` is already available in all `wrapper.py` files and shoudn't be marked as `blocker` error due to undefined variable

![image](https://user-images.githubusercontent.com/72933/70129447-ccc7c500-168f-11ea-9e6e-bd9314dd04b0.png)

Such `SonarCloud` profile marks pull requests into this repo as failed not due to bugs, but due to false positives.

**Comment by iromeo** [comment]
QC / Errors checks which are constantly RED and shows 500 `Blocker` bugs looks really weird..

![image](https://user-images.githubusercontent.com/72933/70129767-6db68000-1690-11ea-916c-ee1e4e7478f9.png)

**Comment by johanneskoester** [comment]
Yes, that is why I deactivated it again. Those blockers are false positives, because it does not know how snakemake invokes those scripts.
