### ISSUE TITLE
Change star/align genomeDir from param to input?

### ISSUE THREAD

**Issue by brcopeland** [snakemake/snakemake-wrappers#364]
The star/align wrapper passes `--genomeDir {snakemake.params.index}` but the associated rule is dependent on star/index.  If this were instead `--genomeDir {snakemake.input.index}` snakemake can infer that it should run a rule using star/index to build the index.

**Comment by fgvieira** [comment]
I believe this has been recently fixed, supporting both `input` and `params` (for backwards compatibility):

https://github.com/snakemake/snakemake-wrappers/blob/c3c8b7255db05365d1adb99aee7263b4b318b88d/bio/star/align/wrapper.py#L40-L42

Can you check if it is working for you?

**Comment by brcopeland** [comment]
I believe it is fixed, thanks @fgvieira.
