### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by nikostr** [snakemake/snakemake-wrappers#370]
Hey, it would be great to get a new tag for the current state of the snakemake wrappers :)

**Comment by johanneskoester** [comment]
Yes, sure. @jafors and @dlaehnemann are still going through some PRs I think. Once they are done, I'd like to make a new release. Unless that is too far in the future. @jafors @dlaehnemann, what do you think?

**Comment by dlaehnemann** [comment]
I'd be fine with an immediate release, as I probably won't have time to actually pick some of the older PRs up in the coming days. So these are probably for the next release, then. But @fgvieira has a couple of PRs that are close to being merged, so maybe he would want them in this next release?

**Comment by fgvieira** [comment]
@dlaehnemann if you are refering to PR #329 and #330, it might take me a couple of days since I need to properly test how python temp folders behave with HPC temp folders. If you are referring to the other open PR, it would be nice to have them included. :smile: (but it is nothing urgent)

**Comment by dlaehnemann** [comment]
Yeah, I think #318 is good to go, just needs @johanneskoester to review again. And #320 and #327 are almost there. So maybe we can wait for these three to be merged.

**Comment by fgvieira** [comment]
All PRs taken care of.
@johanneskoester feel free to make the next release; and thanks for waiting for these last PRs.

**Comment by fgvieira** [comment]
All PRs taken care of.
@johanneskoester feel free to make the next release; and thanks for waiting for these last PRs.

**Comment by dlaehnemann** [comment]
Also, many thanks for your massive contribution efforts!

**Comment by nikostr** [comment]
Great work @dlaehnemann ! Not to be nitpicky, but I think I was responsible for the bwa-mem2 updates :) Anyway, great to have a tag to reference!

**Comment by nikostr** [comment]
Ah, just noticed that the tag is named `v0.75.0` rather than `0.75.0`, which is the format of previous tags, so just updating the wrapper name to `0.75.0/bio/...` from `0.74.0/bio/...` does not work.

**Comment by jafors** [comment]
Ah, good catch. That should be fixed now.

**Comment by dlaehnemann** [comment]
> Great work @dlaehnemann ! Not to be nitpicky, but I think I was responsible for the bwa-mem2 updates :) Anyway, great to have a tag to reference!

Please be. Sorry about that, fixed it just now. Got confused with sooo many updates... :D

**Comment by dlaehnemann** [comment]
> Ah, just noticed that the tag is named `v0.75.0` rather than `0.75.0`, which is the format of previous tags, so just updating the wrapper name to `0.75.0/bio/...` from `0.74.0/bio/...` does not work.

:facepalm: Different projects with different conventions. Thanks for spotting this so quickly.

Generally, I think this is good to be closed. But feel free to reopen, if you spot some more errors.
