### ISSUE TITLE
bowtie2 wrappers fail on OSX (10.15.7)

### ISSUE THREAD

**Issue by hobrien** [snakemake/snakemake-wrappers#372]
This appears to be a problem with the conda recipe for bowtie2 v. 2.4.1:

```
conda activate .snakemake/conda/958e18f4cb4cf1f5eafd39781081e659
bowtie2
```

dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: .snakemake/conda/958e18f4cb4cf1f5eafd39781081e659/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!
Exiting now ...

If I install the latest bowtie2 version (2.4.4) it works without error

**Comment by megancamilla** [comment]
I have hit exactly this same error message with the same OSX version. Is there a way to change which version of bowtie2 the wrapper uses easily?

**Comment by fgvieira** [comment]
Just made a PR with several bug fixes, but could not test it in OSX.
Can you give it a try and let me know?

thanks,

**Comment by johanneskoester** [comment]
PR (#469) has been merged. You can also just try the upcoming release or the master branch. Thank you so much!
