### ISSUE TITLE
Need to refactor parameter names

### ISSUE THREAD

**Issue by troycomi** [snakemake/snakemake-wrappers#38]
**Snakemake version**
5.8.1+12.g85a09c4

**Describe the bug**
Namedlist attributes are used in several wrappers.  Originally reported [here](https://github.com/snakemake/snakemake/issues/151)

**Additional context**
This is the result of making functions in Namedlist class read only.  Any parameters with conflicting names need to be changed to function properly, e.g. index, sort, etc.

**Comment by johanneskoester** [comment]
I think this is fixed now, since namedlist is more relaxed again.
