### ISSUE TITLE
Snakemake does not install conda env from wrappers in subworkflows

### ISSUE THREAD

**Issue by Kevin-Brockers** [snakemake/snakemake-wrappers#413]
**Snakemake version**
snakemake version == 6.10.0
snakemake wrappers == 0.79.0 (fastqc, piccard sort bam, piccard markduplicates)

**Describe the bug**
snakemake does not install conda environments from wrappers in subworkflows.

I have the following structure:
git repo
   |-workflow
      |- rules
         |- rule1.smk
      |- subworkflows
         |- subworkflow1.smk
    |- Snakefile

When I run `snakemake --use-conda` in the git repo root directory, snakemake does not install/ use conda enviroments which are defined in rule1.

I also tried to set the `--conda-prefix .snakemake` then snakemake installs the enviroments but does not use it during the workflow execution.

Any clue how to solve this problem?

**Comment by fgvieira** [comment]
Have not tested wrappers with subworkflows myself, but subworkflows are currently [deprecated](https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#sub-workflows).
But wrappers work fine with [modules](https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#modules). Have you tried it?

**Comment by Kevin-Brockers** [comment]
I switched to modules for several reasons but didn't try to implement wrappers back then.

By now I suspect that snakemake itself was causing the issues, potentially a bug related to relative paths of the conda envs dir... not sure if it's fixed in a newer snakemake release.

If I find time, I can try implement a dummy rule and see if it breaks
