### ISSUE TITLE
Shared memory feature with Snakemake STAR wrapper

### ISSUE THREAD

**Issue by RuiyuRayWang** [snakemake/snakemake-wrappers#420]
This is a duplicate issue of
https://github.com/snakemake/snakemake/issues/1259#issue-1052036783

I'm writing a pipeline using STAR aligner. The task involves sequentially aligning fastq files to the same genome index. To speed up the alignment, I figured that the "shared memory" feature can be used to avoid repeatedly loading and un-loading the genome index.

I have tried and successfully achieved this with STAR pre-built on my machine or STAR built by the integrated package management in snakemake.
I reallly want to use the Snakemake wrapper to do this as it provides better transportability. However, the "STAR align" wrapper requires "fq1" as a minimum input which prevents the "un-load" step of STAR genome index. 

The shell command for STAR to unload genome doesn't have any input or output, which is why the current wrapper cannot be used:

`STAR --genomeLoad Remove --genomeDir {input.index}`

Would it be possible to modify the existing code to make this feature possible?

It may be even better to add a new wrapper sub-commands under star (i.e. `STAR GENOMELOAD`) that incorporates both `--genomeLoad LoadAndExit` and `--genomeLoad Remove` options.

**Comment by RuiyuRayWang** [comment]
Created a pull request for this:
https://github.com/snakemake/snakemake-wrappers/pull/421#issue-1052559722

First time contributing to the repo, correct me if I made any mistakes. Thanks!

**Comment by RuiyuRayWang** [comment]
Closing this issue as Snakemake `service` support has been explicitly developed to address similar jobs at backend. Thanks @johanneskoester!

Check out the relevant links:
[https://github.com/snakemake/snakemake-wrappers/pull/421](url)
[https://github.com/snakemake/snakemake/pull/1413](url)

**Comment by TKMarkCheng** [comment]
Having the same struggle as @moxgreen here. @RuiyuRayWang please can you share your STAR rules for how did you load your genome? I find it awkward since `STAR --genomeLoad` doesn't take in input or outputs, and STAR index takes place in the same workflow which already occupies the genome directory in its output.

**Comment by RuiyuRayWang** [comment]
@TKMarkCheng I have posted a workaround example here: [https://stackoverflow.com/questions/69894230/using-star-shared-memory-module-in-snakemake-for-sequential-alignment-tasks](url). Let me know if you have further questions.

**Comment by fgvieira** [comment]
Thanks for posting it here also!
