### ISSUE TITLE
Use latest / stable version of wrapper rather than specific tag

### ISSUE THREAD

**Issue by vinisalazar** [snakemake/snakemake-wrappers#424]
Hi,

**Is your feature request related to a problem? Please describe.**
Having to manually update the version in the wrapper directive is time consuming. It would be nice to be able to simply specify a latest/stable tag rather than a specific version tag.

**Describe the solution you'd like**
To be able to pass a latest/stable version of the wrapper rather than a specific version tag. e.g.:

```
[...]
# instead of
wrapper:
        "v0.80.1/bio/fastqc"
```
```
# would it be possible to do this instead?
wrapper:
        "latest/bio/fastqc"
```

**Describe alternatives you've considered**
I am not sure if this is already possible? If it is, I'd be happy to put in a PR to the wrapper docs detailing how to do it (if someone can explain it to me first).

**Additional context**
NA

Thank you providing this repository and for any assistance you can provide.

Best,
V

**Comment by johanneskoester** [comment]
Hi, thanks for the request. I'd rather like to fix the "updating is a hassle" issue via a new subcommand of [snakedeploy](https://github.com/snakemake/snakedeploy), instead of allowing something like this. The reason is that you totally loose reproducibility if you would do that.

**Comment by johanneskoester** [comment]
Any PR on snakedeploy for such a functionality would be greatly appreciated.
