### ISSUE TITLE
Not possible to download latest versions of GRCh37

### ISSUE THREAD

**Issue by leachim** [snakemake/snakemake-wrappers#46]
**Snakemake version**
snakemake: 5.9.1
snakemake-wrappers: 0.45.1

**Describe the bug**
It's not possible to download latest versions of GRCh37 build (releases up from 76 on). These are at a different location relative to the main releases. 
`ftp://ftp.ensembl.org/pub/grch37/release-98/fasta/homo_sapiens/dna/` and `ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/` respectively. 

**Logs**
ValueError: Requested sequence does not seem to exist on ensembl FTP servers or servers are unavailable (url ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.grch37.dna.toplevel.fa.gz)

**Comment by johanneskoester** [comment]
You can get an old release for GRCh37. E.g. release 70. That path does not seem very persistent to me. A build name just at the top level, without separation into species first? Are you sure they will keep this stable?

**Comment by ginolhac** [comment]
I successfully used the same version and release **99**
```
rule get_genome:
    output:
        "refs/{build}.fasta"
    params:
        species=config["ref"]["species"],
        datatype="dna",
        build=config["ref"]["build"],
        release="99"
    log:
        "logs/genome_{build}.log"
    wrapper:
        "0.45.1/bio/reference/ensembl-sequence"
```

with in the `config.yaml`

```
ref:
  species: "homo_sapiens"
  build: "GRCh38"
```

**Comment by leachim** [comment]
@ginolhac sorry we are talking specifically about build GRCh37
Alright, I guess that will have to do then. Unfortunately, some of the latest updates to GRCh37 seem to be available only through the alternative path. But, tbh, I don't know how relevant they are and it probably depends on the problem as well.
