### ISSUE TITLE
STAR align zcat does not work on OSX

### ISSUE THREAD

**Issue by vcabeli** [snakemake/snakemake-wrappers#495]
Snakemake 7.8.2
snakemake-wrappers 1.5.0

**Describe the bug**
The parameter `--readFilesCommand` is hard-coded to `zcat` in the STAR/align wrapper, which does not work on OSX : 

https://github.com/snakemake/snakemake-wrappers/blob/36842760dddc71e321c93cb11d4c39840cdd2a84/bio/star/align/wrapper.py#L35-L38

**Logs**
`zcat: can't stat: .test/macophage/fikt_C.1.fastq.gz (.test/macophage/fikt_C.1.fastq.gz.Z): No such file or directory
zcat: can't stat: .test/macophage/fikt_C.2.fastq.gz (.test/macophage/fikt_C.2.fastq.gz.Z): No such file or directory`

and we cannot override the `--readFilesCommand` to use `gunzip -c` instead of `zcat` : 
`EXITING: FATAL INPUT ERROR: duplicate parameter "readFilesCommand" in input "Command-Line"
SOLUTION: keep only one definition of input parameters in each input source`

**Comment by fgvieira** [comment]
Can you send an example of the command line on OSX? Would `--readFilesCommand gunzip -c` work?

**Comment by vcabeli** [comment]
Yes, it seems to work for me !

**Comment by fgvieira** [comment]
I'd say that should also work on linux and, if so, I guess you can just replace `zcat` with `gunzip -c`.
Just submit a PR and I'll approve it.

**Comment by fgvieira** [comment]
Fixed and closing.
