### ISSUE TITLE
markduplicates requires log file

### ISSUE THREAD

**Issue by ManavalanG** [snakemake/snakemake-wrappers#50]
**Snakemake version**
Snakemake - 5.6.0
Snakemake wrapper - 0.47.0

**Describe the bug**
Rule [`markduplicates`](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/picard/markduplicates/wrapper.py) uses `{snakemake.log}` directly in file, instead of utilizing `snakemake.log_fmt_shell`. This necessiates the use of file in `log:` directive and its absence results in job ending in error. 

Relevant code:
https://github.com/snakemake/snakemake-wrappers/blob/dfe6d54068fff4ada259af411f0782b8bbd29ea3/bio/picard/markduplicates/wrapper.py#L10-L14

**Logs**
```
/bin/bash: -c: line 0: syntax error near unexpected token `newline'
/bin/bash: -c: line 0: `set -euo pipefail;  picard MarkDuplicates REMOVE_DUPLICATES=true  TMP_DIR=/tmp INPUT=a.sorted.bam OUTPUT=dedup/a.bam METRICS_FILE=dedup/a.metrics.txt &>'
Traceback (most recent call last):
  File "/up/.snakemake/scripts/tmp075fw1hj.wrapper.py", line 14, in <module>
    shell("picard MarkDuplicates {snakemake.params} INPUT={snakemake.input} "
  File "/mnt/snakemake/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
```

**Minimal example**
```py
rule mark_duplicates:
    input:
        "a.sorted.bam"
    output:
        bam="dedup/a.bam",
        metrics="dedup/a.metrics.txt"
    log:
        "/logs/a.log"
    wrapper:
        "0.47.0/bio/picard/markduplicates"
```

**Additional context**

**Comment by johanneskoester** [comment]
Thank you! Should be fixed with PR #64.
