### ISSUE TITLE
bwa-mem2 incorrect index

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake-wrappers#522]
The [wrapper 1.7.0 for bwa-mem2](https://snakemake-wrappers.readthedocs.io/en/v1.7.0/wrappers/bwa-mem2/mem.html) contains the following code:

```.py
index = snakemake.input.get("index", "")
if isinstance(index, str):
    index = path.splitext(snakemake.input.idx)[0]
else:
    index = path.splitext(snakemake.input.idx[0])[0]
```

which mixes `index` and `idx`, clearly a bug.

PS: The command uses `samtools sort`, which would benefit from [offering a temp directory](https://snakemake-wrappers.readthedocs.io/en/0.85.0/wrappers/bwa/mem.html).

**Comment by christopher-schroeder** [comment]
@dlaehnemann @johanneskoester @tdayris 
Blame shows you as author of this snippet. I can modify / fix that, but I don't see the point having this at all. bwa mem 2 requires a list of files as index. Allowing a single string implies that the user may only provide one of the index files.
It would be even cleaner if we require input.ref (fasta file) and input.index (all the index files).

**Comment by christopher-schroeder** [comment]
I slept on it and realised that I'm going to modify the wrapper for cram output anyway. Since samtools sort needs the reference, input.ref makes sense.

**Comment by fgvieira** [comment]
I agree, all input files needed by the rule should be explicitely specified.

**Comment by lczech** [comment]
Bump to remove stale label.

**Comment by votti** [comment]
Using `snakemake==8.16.0` this silent bug has become an error.

Running the tests with this version yields:
```
Traceback (most recent call last):
  File "/home/vitoz/Git/snakemake-wrappers/bio/bwa-mem2/mem/test/.snakemake/scripts/tmpecj0nw1t.wrapper.py", line 35, in <module>
    index = path.splitext(snakemake.input.idx)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not Namedlist
RuleException:
CalledProcessError in file /home/vitoz/Git/snakemake-wrappers/bio/bwa-mem2/mem/test/Snakefile, line 19:
Command 'source /home/vitoz/mambaforge/envs/snakemake-wrappers-development/bin/activate '/home/vitoz/Git/snakemake-wrappers/bio/bwa-mem2/mem/test/.snakemake/conda/5b337243f0e141f0d983821f93eb1ce9_'; set -euo pipefail;  python /home/vitoz/Git/snakemake-wrappers/bio/bwa-mem2/mem/test/.snakemake/scripts/tmpecj0nw1t.wrapper.py' returned non-zero exit status 1.
```

The reason is that before this  bug was silent because:
`snakemake.input.index` would always be a available as `functools.partial(<function Namedlist._used_attribute at 0x73ac4dbc0c20>, _name='index')` or similar.
Thus the predicate that it was not a `str` was always true.
Now this changed, causing the bug to surface.

For me this broke a workflow, thus I opened a PR.

**Comment by dlaehnemann** [comment]
This should be clsoed by #3101. Feel free to reopen if this re-occurs.
