### ISSUE TITLE
SnpEff - (unnecessary) Multiple BCFTools calls

### ISSUE THREAD

**Issue by tdayris-perso** [snakemake/snakemake-wrappers#54]
Hi,

**Snakemake version**
Snakemake: bioconda:snakemake=5.10.0 (latest)

Snakemake-wrappers: 0.49.0 (latest)
However, the issue is raised since commit: [d90abc3](https://github.com/snakemake/snakemake-wrappers/commit/d90abc388ed573be3cf9c3d011e164b694ee509c#diff-9a7f2fd63fafede6dd8b6d3539fe5ba8), which includes a modification of the file  `wrapper.py` of SnpEff

**Describe the bug**

In the file `bio/snpeff/wrapper.py`, he lines [22](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/snpeff/wrapper.py#L22) to [24](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/snpeff/wrapper.py#L24) overloads the value of the variable `incalls` :

```
incalls = snakemake.input[0]
if incalls.endswith(".bcf"):
    incalls = "<(bcftools view {})".format(incalls)
```

However, last modifications includes `bcftools` in the final shell line, at line [40](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/snpeff/wrapper.py#L40)

```
shell(
    "(bcftools view {incalls} | "
    "snpEff {data_dir} {stats_opt} {csvstats_opt} {extra} "
    "{snakemake.params.reference} "
    "{outprefix} > {outcalls}) {log}"
)
```

So, with bcf files, the final command line is:

`(bcftools view <(bcftools view {incalls}) | snpEff ...`

**Additional context**
Additionally, this behaviour leads to the systematic use of BCFTools piped with SnpEff. This wrapper uses at least two threads while running (one for each tools).

**Solution**
Please remove the lines 23 and 24, since they are no longer useful.

Many thanks in advance.

**Comment by johanneskoester** [comment]
Good catch! See PR #63.
