### ISSUE TITLE
bwa-mem2 mem wrapper doesn't work 

### ISSUE THREAD

**Issue by alyazeeditalal** [snakemake/snakemake-wrappers#541]
The bwa-mem2 wrapper script did not work for me. I read from other reported issues that a yaml file specifing the right python environment is required for each wrapper. Though, how can we find the right python version for each wrapper? 

here is the error message 
/home/alyazeedit/miniconda3/envs/snakemake/bin/python3.10 /home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/scripts/tmp2ws9o9w4.wrapper.py
(bwa-mem2 mem -t 4 -R '@RG\tID:Pool_Dead_1\tSM:Pool_Dead_1' r resources/reads/Pool_Dead_1_R1.fastq.gz resources/reads/Pool_Dead_1_R2.fastq.gz | picard SortSam  INPUT=/dev/stdin OUTPUT=results/alignments/Pool_Dead_1.sorted.bam SORT_ORDER=coordinate)  2> logs/bwa_mem2_alignments/Pool_Dead_1.log
Traceback (most recent call last):
  File "/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/scripts/tmp2ws9o9w4.wrapper.py", line 72, in <module>
    shell(
  File "/home/alyazeedit/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 296, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  (bwa-mem2 mem -t 4 -R '@RG\tID:Pool_Dead_1\tSM:Pool_Dead_1' r resources/reads/Pool_Dead_1_R1.fastq.gz resources/reads/Pool_Dead_1_R2.fastq.gz | picard SortSam  INPUT=/dev/stdin OUTPUT=results/alignments/Pool_Dead_1.sorted.bam SORT_ORDER=coordinate)  2> logs/bwa_mem2_alignments/Pool_Dead_1.log' returned non-zero exit status 127.
[Wed Aug 17 15:36:45 2022]
Error in rule bwa_mem2_mem:
    jobid: 12
    output: results/alignments/Pool_Dead_1.sorted.bam
    log: logs/bwa_mem2_alignments/Pool_Dead_1.log (check log file(s) for error message)
    conda-env: /home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493

RuleException:
CalledProcessErrorin line 48 of /home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/rules/alignment.smk:
Command 'set -euo pipefail;  /home/alyazeedit/miniconda3/envs/snakemake/bin/python3.10 /home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/scripts/tmp2ws9o9w4.wrapper.py' returned non-zero exit status 1.
  File "/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/rules/alignment.smk", line 48, in __rule_bwa_mem2_mem
  File "/home/alyazeedit/miniconda3/envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-08-17T153639.297195.snakemake.log

**Snakemake version**
 conda 4.12.0
snakemake  7.12.1 
wrapper: 
          "v1.8.0/bio/bwa-mem2/mem"

**Comment by fgvieira** [comment]
What does the log say?

**Comment by alyazeeditalal** [comment]
This is the content of the log file: 

/bin/bash: bwa-mem2: command not found
/bin/bash: picard: command not found

**Comment by fgvieira** [comment]
How are you running your workflow?

**Comment by alyazeeditalal** [comment]
Here is the rule I used to run the alignment. 

rule bwa_mem2_mem:
    """
    Align the raw reads to the reference using bwa_mem2_mem
    """
    input:      
        reads= ["resources/reads/{sample}_{rep}_R1.fastq.gz", "resources/reads/{sample}_{rep}_R2.fastq.gz"], 
        idx= "resources/genome/VectorBase-58_AfunestusFUMOZ_Genome.fasta",
    output: 
        temp("results/alignments/{sample}_{rep}.sorted.bam")
    log:
        "logs/bwa_mem2_alignments/{sample}_{rep}.log"
    params:
        extra=r"-R '@RG\tID:{sample}_{rep}\tSM:{sample}_{rep}'",
        sort="picard",  
        sort_order="coordinate", 
    threads: 16
    wrapper:
        "v1.8.0/bio/bwa-mem2/mem"

**Comment by fgvieira** [comment]
But what snakemake make command did you use? Did you use `--use-conda`?

**Comment by alyazeeditalal** [comment]
Yes, and got the same error message.

**Comment by fgvieira** [comment]
From the error message, it could be someting with the conda env. Try running:
```
conda activate /home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493
bwa-mem2
picard SortSam
```

Do you get the same error?

**Comment by alyazeeditalal** [comment]
After activating the conda environment both of 
bwa-mem2 and picard sortsam work. 
Though when running snakemake pipeline I get the same error message as above. 

>(/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493) alyazeedit@neptune:~/lstm_data/snakemake_FANGvsFUMOZ_poolseq$ bwa-mem2


Looking to launch executable "/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493/bin/bwa-mem2.avx512bw", simd = .avx512bw
Launching executable "/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493/bin/bwa-mem2.avx512bw"
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment


> (/home/alyazeedit/lstm_data/snakemake_FANGvsFUMOZ_poolseq/.snakemake/conda/c67834db978607322ea1b3c6ba6cf493) alyazeedit@neptune:~/lstm_data/snakemake_FANGvsFUMOZ_poolseq$ snakemake --core 8 -p --use-conda all_counts

Still get the same error message as above.

**Comment by fgvieira** [comment]
Can you send me a minimal example and how you run it? Maybe also some small example fastqs.
So I can try to reproduce your error.

**Comment by alyazeeditalal** [comment]
I ran snamemake from inside a conda environment I created only for snakemake following the installation instructions in the snakemake website.

**Comment by fgvieira** [comment]
Can you send me a minimal example so I can reproduce the error?

**Comment by alyazeeditalal** [comment]
I have emailed you an example of my fasta files, and snakemake file to your email fgvieira@snm.ku.dk

**Comment by fgvieira** [comment]
Hi @alyazeeditalal,

did you manage to get it to work?
If so, could share briefly what the problem was? Just in case other users have the same problem as you.

thanks,

**Comment by alyazeeditalal** [comment]
Thanks for updating the wrapper. 

The wrapper is working now for my application. In my case, it was better to make two separate rules for alignment and sorting, than doing it all in one rule. When the alignment and the sorting were on one rule the issue of running out of desk space was reoccurring, despite the direction of $tmp files to a directory with more desk space.
