### ISSUE TITLE
Example Snakemake rule wrapper attribute for DADA2_QUALITY_PROFILES is incorrect

### ISSUE THREAD

**Issue by mtmcgowan** [snakemake/snakemake-wrappers#622]
**Snakemake version**
Snakemake = 7.16.0
Snakemake-wrapper  = v1.17.3

**Describe the bug**
Using the example wrapper attribute for DADA2_QUALITY_PROFILES ("v1.17.3/bio/dada2/quality-profile") causes a 404 error when Conda tries to pull the wrapper file. 

The http link that causes the 404 error appears like it points to a python wrapper instead of an R wrapper.

Updating the wrapper attribute in my Snakefile to  "v1.17.3/bio/dada2/quality-profile/wrapper.R" appears to solve the problem.

**Logs**
Did not collect logs

**Minimal example**
rule dada2_quality_profile_pe:
    input:
        expand("{project_dir}/{sample_name}-{rep}_{orientation}_001.fastq.gz",
            project_dir=config['project_dir'],
            orientation=[1, 2],
            allow_missing=True)
    output:
        "reports/dada2/quality-profile/{sample_name}-{rep}-quality-profile.png"
    log:
        "reports/dada2/quality-profile/{sample_name}-{rep}-quality-profile.log"
    wrapper:
        "v1.17.3/bio/dada2/quality-profile"

**Additional context**
None

**Comment by fgvieira** [comment]
Tried running the test case for that wrapper, and it works fine.
Can you give it a try?

**Comment by fgvieira** [comment]
I tried to run the example, but got another error:
```
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object './snakemake-wrappers/bio/dada2/quality-profile/test/.snakemake/conda/39215bc162aa14d49e07c3e5e7f3f64a_/lib/R/library/jpeg/libs/jpeg.so':
  libjpeg.so.9: cannot open shared object file: No such file or directory
Execution halted

```

**Comment by fgvieira** [comment]
I think that what is happening is that `snakemake` looks for the `wrapper.py` file and, only after failing three times, tries the `wrapper.R` file.
@johanneskoester can you confirm this behaviour?

If so, it is just a bit misleading error message...
