### ISSUE TITLE
Error: Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml

### ISSUE THREAD

**Issue by nicolau** [snakemake/snakemake-wrappers#884]
**Snakemake version**
7.18.1

**Describe the bug**
I'm trying to run a snakemake pipeline for RNA-Seq and using snakemake wrappers for almost all packages. After to start the execution with command "snakemake --use-conda --cores 6". The multiqc and fastqc rule are:

```
rule fastqc:
    input: ["../resources/reads/{sample}_R1_001.fastq.gz", "../resources/reads/{sample}_R2_001.fastq.gz"]
    output:
        html="results/qc/fastqc/{sample}.html",
        zip="results/qc/fastqc/{sample}_fastqc.zip" # the suffix _fastqc.zip is necessary for multiqc to find the file. If not using multiqc, you are free to choose an arbitrary filename
    params: "--quiet"
    # version: shell("fastqc --version")
    # log: "logs/fastqc/{sample}.log"
    threads: config["params"]["general"]["threads"]
    wrapper: config["wrapper_version"] + "/bio/bio/fastqc"

# Depends on: rule fastqc
rule multiqc:
    input: expand("results/qc/fastqc/{sample}.html", sample=SAMPLES)
    output: "results/qc/multiqc_report.html"
    params: ""  # Optional: extra parameters for multiqc.
    log: "logs/multiqc.log"
    wrapper: config["wrapper_version"] + "/bio/bio/multiqc"
```

**Logs**
`Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml
HTTPError: 404 Client Error: Not Found for url: https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml, attempt 1/3 failed - retrying in 3 seconds...
Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml
HTTPError: 404 Client Error: Not Found for url: https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml, attempt 2/3 failed - retrying in 6 seconds...
Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml
HTTPError: 404 Client Error: Not Found for url: https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml, attempt 3/3 failed - giving up!
WorkflowError:
Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml
HTTPError: 404 Client Error: Not Found for url: https://github.com/snakemake/snakemake-wrappers/raw/v1.19.0/bio/bio/multiqc/environment.yaml
  File "/opt/conda/envs/lncrna/lib/python3.10/site-packages/reretry/api.py", line 218, in retry_call      
  File "/opt/conda/envs/lncrna/lib/python3.10/site-packages/reretry/api.py", line 31, in __retry_internal `

**Comment by fgvieira** [comment]
I think your code should be:
```
wrapper: config["wrapper_version"] + "/bio/multiqc"
```

**Comment by nicolau** [comment]
You're right @fgvieira. Thank you very much.
