### ISSUE TITLE
Trim galore inconsitent output filenames

### ISSUE THREAD

**Issue by SilasK** [snakemake/snakemake-wrappers#967]
Trim galore internally defines output filenames from input filenames. This can lead to inconsistencies with the output filenaming. 

Wrapper:
https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/trim_galore/pe.html

Idealy one should use

--basename <PREFERRED_NAME>

Use PREFERRED_NAME as the basename for output files, instead of deriving the filenames from the input files. Single-end data would be called PREFERRED_NAME_trimmed.fq(.gz), or PREFERRED_NAME_val_1.fq(.gz) and PREFERRED_NAME_val_2.fq(.gz) for paired-end data. --basename only works when 1 file (single-end) or 2 files (paired-end) are specified, but not for longer lists.

**Comment by SilasK** [comment]
Also threads are not used for trim galore

**Comment by fgvieira** [comment]
Do you think you could make a PR with the changes?

**Comment by SilasK** [comment]
No sorry.
