### ISSUE TITLE
Qualimap remote package is not installed

### ISSUE THREAD

**Issue by ltalignani** [snakemake/snakemake-wrappers#975]
I am still waiting for its installation:

<img width="1119" alt="Capture d’écran 2023-01-12 à 06 34 11" src="https://user-images.githubusercontent.com/53080888/211985916-374bb426-fcdf-4d0d-9032-15cf5f665e39.png">

My pipeline is completely blocked at this step, waiting for Qualimap installation. 
I am using the latest version of snakemake and the stable version of snakemake-wrappers

There is also another problem with the Qualimap wrapper's name. There is two QUALIMAP RNA, but the first one is for WGS, RNA, CHIP-Seq...

**Comment by fgvieira** [comment]
It could be a conda/bioconda issue... can you install it on a existing conda environment?

**Comment by ltalignani** [comment]
I am currently using a conda environment for snakemake (6.12.3). I run my snakemake pipeline into it. My pipeline use massively snakemake wrappers for Picard Tools (MarkDuplicatesSpark, mergevcfs), GATK (RealignerTargetCreator, IndelRealigner, UnifiedGenotyper, variantfiltration),  samtools (idxstats, flagstat, tabix, bgzip), and there is no problem with these wrappers.

**Comment by ltalignani** [comment]
I installed Qualimap in an environment and it works: 
<img width="1359" alt="Capture d’écran 2023-01-12 à 16 43 04" src="https://user-images.githubusercontent.com/53080888/212112638-4699e53b-35dd-48fe-a92f-3ec37d22791d.png">
but not the wrapper.

**Comment by ltalignani** [comment]
I was using the wrapper "v1.21.1-3-g1bd26948/bio/qualimap/bamqc". I installed it yesterday. And now it's version "v1.21.2/bio/qualimap/bamqc". 

I will try with this version and let you the result when it will finish.

**Comment by fgvieira** [comment]
Did you manage to try the new wrapper version? Does it work?

**Comment by fgvieira** [comment]
I just tried running the wrapper test and it worked fine. Closing this issue since it could have been some issue with conda.
