### ISSUE TITLE
Mutect2 issue that raises false positive calls by 20%

### ISSUE THREAD

**Issue by tdayris** [snakemake/snakemake-wrappers#991]
**Is your feature request related to a problem? Please describe.**
Knowing the open issue on GATK github: [Mutect2: drop in SNV specificity/precision between v.4.1.8.1 and 4.1.9.0)](https://github.com/broadinstitute/gatk/issues/7921)

Knowing the final answer of GATK team: 

> Sorry for the long wait on this issue, which we do take seriously! Unfortunately as mentioned above we have extremely limited resources for Mutect2 maintenance at the moment due to our focus on Mutect3, which we see as the long-term solution to this and other issues. You should definitely continue to run 4.1.8.0 until this is resolved, if at all possible.

**Describe the solution you'd like**

Drop Mutect2 wrapper environment from 4.2 to 4.1.8.0.

**Describe alternatives you've considered**

Add a warning on documentation.

**Additional context**

There is no known release date for Mutect3.

**Comment by fgvieira** [comment]
Has this been fixed on version `4.4.0.0`?

**Comment by tdayris** [comment]
As far as I know, it has not been corrected. A new PoN has been given to the community however.

**Comment by fgvieira** [comment]
If it is a matter of choosing what GATK version to use, the user can just use an older wrapper version, no?
